"""new fields in user model

Revision ID: 1382a6d410f8
Revises: bccc5bdcce7c
Create Date: 2019-10-18 02:06:09.672820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1382a6d410f8'
down_revision = 'bccc5bdcce7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
